defaults:
  - _self_
  - env: lunar_lander
  - agent: ddpg
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
device: ${device}

# Logging configuration
tensorboard:
  enabled: false  # Whether to use tensorboard logging

wandb:
  project: rl
  entity: null  # Set your wandb entity here
  mode: online  # Set to disabled to turn off logging
  name: ${agent.name}_${env.name}_${seed}

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num} 