defaults:
  - _self_
  - env: lunar_lander
  - agent: ddpg
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
device: ${device}

# Save configuration
save:
  metrics_freq: 200  # Save metrics every N episodes
  model_freq: 200   # Save model checkpoints every N episodes
  metrics_dir: "metrics"  # Directory for metric files
  model_dir: "models"    # Directory for model checkpoints

# Logging configuration
tensorboard:
  enabled: false  # Whether to use tensorboard logging

wandb:
  project: rl
  entity: null  # Set your wandb entity here
  mode: online  # Set to disabled to turn off logging
  name: ${agent.name}_${env.name}_${seed}

hydra:
  run:
    dir: outputs/${agent.name}_${env.name}_${seed}
  sweep:
    dir: multirun/${agent.name}_${env.name}_${seed}
    subdir: ${hydra.job.num} 